language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - DATA=Kay-BUILD-SNAPSHOT
    - DATA=Lovelace-BUILD-SNAPSHOT
    - BOOT=2.0.0.BUILD-SNAPSHOT
    - BOOT=2.0.0.BUILD-SNAPSHOT DATA=Kay-BUILD-SNAPSHOT
    - BOOT=2.0.0.BUILD-SNAPSHOT DATA=Lovelace-BUILD-SNAPSHOT

addons:
  apt:
    packages:
    - oracle-java8-installer

services:
  - redis-server

cache:
  directories:
    - $HOME/.m2

sudo: false

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml


install: true

script:
 - git clone https://github.com/spring-projects/spring-data-examples.git
 - ./run.sh
